// Writes src/version.ts with the current git commit + date. Runs automatically
// before `npm start` / `npm run build` (see package.json) and in CI before the
// production build. The file is gitignored — it's generated, not committed.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

function git(args, fallback) {
  try {
    return execSync(`git ${args}`, { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

const sha = git('rev-parse --short HEAD', 'dev');
const date = git('show -s --format=%cs HEAD', new Date().toISOString().slice(0, 10));

const body = `// Generated by scripts/gen-version.mjs — do not edit; not committed.
export const APP_VERSION = '${sha}';
export const BUILD_DATE = '${date}';
`;

writeFileSync(new URL('../src/version.ts', import.meta.url), body);
console.log(`version.ts -> ${sha} (${date})`);
