// Writes src/version.ts with the app version (from package.json) and the date
// of the latest commit. Runs automatically before `npm start` / `npm run build`
// (see package.json) and in CI before the production build. The generated file
// is gitignored — it's a build artifact, not committed.
//
// To release a new version, bump "version" in package.json (e.g. 1.0.0 -> 1.1.0).
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

function git(args, fallback) {
  try {
    return execSync(`git ${args}`, { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const version = pkg.version || '0.0.0';
const date = git('show -s --format=%cs HEAD', new Date().toISOString().slice(0, 10));

const body = `// Generated by scripts/gen-version.mjs — do not edit; not committed.
export const APP_VERSION = '${version}';
export const BUILD_DATE = '${date}';
`;

writeFileSync(new URL('../src/version.ts', import.meta.url), body);
console.log(`version.ts -> v${version} (${date})`);
